// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyExKFJOguJLRZzl5t9QhmWbMsCzqEPvw',
    appId: '1:57292678792:web:b84b70d6dbfe40b7f6613d',
    messagingSenderId: '57292678792',
    projectId: 'smartboard-go',
    authDomain: 'smartboard-go.firebaseapp.com',
    storageBucket: 'smartboard-go.firebasestorage.app',
    measurementId: 'G-K4S0ZTCEH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzp9JWdvKfKwyFRW_Hut96O9TFiIr7SSs',
    appId: '1:57292678792:android:38a1b5055addcdf9f6613d',
    messagingSenderId: '57292678792',
    projectId: 'smartboard-go',
    storageBucket: 'smartboard-go.firebasestorage.app',
  );
}
